#!/bin/bash

#set -x

export SVDIR=/container/services/

services=$(find /container/services/* -type d -exec basename {} \;)

for srv in ${services}; do
    /usr/bin/sv status ${srv}
    if [ $? -ne 0 ]; then
        exit 1
    fi
done

exit 0
