#!/bin/bash

#set -x

export SVDIR=/container/services/

services=$(find /container/services/ -maxdepth 1 -type d -exec basename {} \; | grep -v services)

for srv in ${services}; do
    /usr/bin/sv status ${srv}
    if [ $? -ne 0 ]; then
        exit 1
    fi
done

exit 0
