#!/bin/bash

export SVDIR=/container/services/

services=$(find /container/services/ -maxdepth 1 -type d -exec basename {} \; | grep -v services | grep -v logrotate)

for srv in ${services}; do
    /usr/bin/sv hup ${srv}
    if [ $? -ne 0 ]; then
        exit 1
    fi
done

exit 0
