stages:
  - build
  - tests
  - publish_images

variables:
  CONTAINER_BASE_VERSION: '0.3.0'
  DOCKER_REGISTRY_HOST: '83l02d2f.gra5.container-registry.ovh.net'

#-----------------------------------------
build_image:
  stage: build
  tags:
    - shell
  variables:
    BUILD_OPTS: '--force-rm --no-cache'
  script:
    - docker build ${BUILD_OPTS} -t article714/container-base-debian:${CONTAINER_BASE_VERSION} -t ${DOCKER_REGISTRY_HOST}/article714/container-base-debian:${CONTAINER_BASE_VERSION} --build-arg CONTAINER_BASE_VERSION=${CONTAINER_BASE_VERSION} .

#------------------------------------------
# QCheck (TODO)

#------------------------------------------
# Tests

test_image:
  stage: tests
  image:
    name: article714/container-base-debian:${CONTAINER_BASE_VERSION}
  tags:
    - docker
  script:
    - id
    - export SVDIR=/container/services
    - runsvdir -P $SVDIR &
    - ls -alrt /var/log/
    - sv restart rsyslogd
    - sv stop rsyslogd
    - ls -alrt /var/log/
    - sv status cron
    - sv stop cron

#------------------------------------------
# Publish
publish_image:
  stage: publish_images
  tags:
    - shell
  only:
    refs:
      - production
  script:
    - docker push ${DOCKER_REGISTRY_HOST}/article714/container-base-debian:${CONTAINER_BASE_VERSION}
