include:
  - project: 'article714/build-tools'
    ref: master
    file: 'ci/docker-job-templates.yml'

stages:
  - build
  - qcheck
  - security
  - test
  - publish

variables:
  IMAGE_VERSION: '0.7.0'
  IMAGE_NAME: 'debian-based-container'

#-----------------------------------------
build_image:
  extends: .build_image

#------------------------------------------
# QCheck (TODO)

#------------------------------------------
# Security Scanners (TODO)

#------------------------------------------
# Tests

test_image:
  extends: .test_image
  script:
    - id
    - export SVDIR=/container/services
    - runsvdir -P $SVDIR &
    - ls -alrt /var/log/
    - sv restart rsyslogd
    - sv stop rsyslogd
    - ls -alrt /var/log/
    - sv status cron
    - sv stop cron

#------------------------------------------
# Publish

publish_release:
  extends: .publish_image
  variables:
    IMAGE_TAG: ${CI_COMMIT_TAG}
  rules:
    - if: $CI_COMMIT_TAG

publish_latest:
  extends: .publish_image
  variables:
    IMAGE_TAG: 'latest'
  only:
    refs:
      - production
