stages:
  - build
  - tests
  - publish_images

variables:
  CONTAINER_BASE_VERSION: '0.2.0'
  DOCKER_REGISTRY_HOST: '83l02d2f.gra5.container-registry.ovh.net'

#-----------------------------------------
build_image:
  stage: build
  tags:
    - shell
  variables:
    BUILD_OPTS: '--force-rm --no-cache'
  script:
    - docker build ${BUILD_OPTS} -t certificare/container-base-debian:${CONTAINER_BASE_VERSION} -t ${DOCKER_REGISTRY_HOST}/certificare/container-base-debian:${CONTAINER_BASE_VERSION} --build-arg CONTAINER_BASE_VERSION=${CONTAINER_BASE_VERSION} .

#------------------------------------------
# QCheck (TODO)

#------------------------------------------
# Tests

test_image:
  stage: tests
  image:
    name: certificare/container-base-debian:${CONTAINER_BASE_VERSION}
  tags:
    - docker
  script:
    - echo "TODO"

#------------------------------------------
# Publish
publish_image:
  stage: publish_images
  tags:
    - shell
  only:
    refs:
      - production
  script:
    - docker push ${DOCKER_REGISTRY_HOST}/certificare/container-base-debian:${CONTAINER_BASE_VERSION}
